# Install and test each package on a Docker image ocaml/opam2:alpine

language: c
sudo: required
services:
  - docker
env:
  global:
    - OPAMBUILDTEST="true"
  matrix:
    # Note that PRE_INSTALL_HOOK assumes that PACKAGE contains its version.
    - PACKAGE="camlpdf.2.2.1+satysfi" OCAML_VERSION="4.06"
    - PACKAGE="otfm.0.3.0+satysfi" OCAML_VERSION="4.06"
    - PACKAGE="otfm.0.3.1+satysfi" OCAML_VERSION="4.06"
    - PACKAGE="otfm.0.3.2+satysfi" OCAML_VERSION="4.06"
    - PACKAGE="satysfi.0.0.3" OCAML_VERSION="4.06"
    - PACKAGE="yojson.1.4.1+satysfi" OCAML_VERSION="4.06"
install:
  - DOCKERFILE=".travis-Dockerfile.template"
  - sed -i "s/%ocaml_version%/${OCAML_VERSION}/g" "${DOCKERFILE}"
  - sed -i "s/%package%/${PACKAGE}/g"             "${DOCKERFILE}"
  - sed -i "s/%opambuildtest%/${OPAMBUILDTEST}/g" "${DOCKERFILE}"
  - docker build --tag satysfi/satysfi-external-repo --file "${DOCKERFILE}" .
script: docker run satysfi/satysfi-external-repo
