# Documentation: https://github.com/ocaml/ocaml-ci-scripts/blob/master/README-travis-runner.md

language: c
sudo: required
services:
  - docker
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script:
  - set -e
  - opam lint "./packages/${PACKAGE_NAME%%.*}/${PACKAGE}/"
  - bash -ex ./.travis-docker.sh
env:
  global:
    - DISTRO="alpine"
    - PRE_INSTALL_HOOK="opam repo add satysfi-external && opam update"
    - TESTS="true"
  matrix:
    # Note that `script` assumes that PACKAGE contains its version.
    - PACKAGE="camlpdf.2.2.1+satysfi" OCAML_VERSION="4.05.0"
    - PACKAGE="camlpdf.2.2.1+satysfi" OCAML_VERSION="4.06.0"
    - PACKAGE="otfm.0.3.0+satysfi" OCAML_VERSION="4.05.0"
    - PACKAGE="otfm.0.3.0+satysfi" OCAML_VERSION="4.06.0"
